mongo_hc now writes to file.  vim now compiles scripts when f5 is pressed in vim

diff --git a/tapioca_compile b/tapioca_compile
--- a/tapioca_compile
+++ b/tapioca_compile
@@ -9,6 +9,7 @@ case $EXTENSION in
 		javac $FILE ;;
 	pl)
 		perl $FILE ;;
+
 	*)
-		echo "Can not find file format $EXTENSION" ;;
+		./$FILE || echo "Could not run the file" ;;
 esac
